// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Feb 12 13:44:55 2004

#include "layout.h"


ServerFrame::ServerFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxCAPTION|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxSYSTEM_MENU|wxRESIZE_BORDER|wxFRAME_NO_TASKBAR)
{
    // begin wxGlade: ServerFrame::ServerFrame
    notebook_base = new wxNotebook(this, -1, wxDefaultPosition, wxDefaultSize, 0);
    notebook_base_pane_status = new wxPanel(notebook_base, -1);
    label_connection_status = new wxStaticText(notebook_base_pane_status, -1, wxT("Eastex: Connected"), wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE);
    list_ctrl_client_status = new wxListCtrl(notebook_base_pane_status, -1, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxSUNKEN_BORDER);

    set_properties();
    do_layout();
    // end wxGlade
}


void ServerFrame::set_properties()
{
    // begin wxGlade: ServerFrame::set_properties
    SetTitle(wxT("JNetDial Server"));
    // end wxGlade
}


void ServerFrame::do_layout()
{
    // begin wxGlade: ServerFrame::do_layout
    wxBoxSizer* sizer_background = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_status = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_client_status = new wxStaticBoxSizer(new wxStaticBox(notebook_base_pane_status, -1, wxT("Client Status")), wxHORIZONTAL);
    wxStaticBoxSizer* sizer_connection_status = new wxStaticBoxSizer(new wxStaticBox(notebook_base_pane_status, -1, wxT("Connection Status")), wxHORIZONTAL);
    sizer_connection_status->Add(label_connection_status, 0, wxALL|wxEXPAND, 1);
    sizer_status->Add(sizer_connection_status, 0, wxALL|wxEXPAND, 3);
    sizer_client_status->Add(list_ctrl_client_status, 1, wxEXPAND, 0);
    sizer_status->Add(sizer_client_status, 1, wxALL|wxEXPAND, 3);
    notebook_base_pane_status->SetAutoLayout(true);
    notebook_base_pane_status->SetSizer(sizer_status);
    sizer_status->Fit(notebook_base_pane_status);
    sizer_status->SetSizeHints(notebook_base_pane_status);
    notebook_base->AddPage(notebook_base_pane_status, wxT("Status"));
    sizer_background->Add(new wxNotebookSizer(notebook_base), 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_background);
    sizer_background->Fit(this);
    sizer_background->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}








ClientFrame::ClientFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: ClientFrame::ClientFrame
    notebook_client = new wxNotebook(this, -1, wxDefaultPosition, wxDefaultSize, 0);
    notebook_client_pane_stayonline = new wxPanel(notebook_client, -1);
    notebook_client_pane_server = new wxPanel(notebook_client, -1);
    label_connection_status = new wxStaticText(notebook_client_pane_server, -1, wxT("Eastex: Connected"), wxDefaultPosition, wxDefaultSize, wxST_NO_AUTORESIZE);
    button_client_connect = new wxButton(notebook_client_pane_server, -1, wxT("Connect"));
    button_client_disconnect = new wxButton(notebook_client_pane_server, -1, wxT("Disconnect"));
    checkbox_enable_stayonline = new wxCheckBox(notebook_client_pane_stayonline, -1, wxT("Enable StayOnline"));
    label_stayonline_start_time = new wxStaticText(notebook_client_pane_stayonline, -1, wxT("Start Time:"));
    text_ctrl_stayonline_start_time = new wxTextCtrl(notebook_client_pane_stayonline, -1, wxT(""));
    label_stayonline_end_time = new wxStaticText(notebook_client_pane_stayonline, -1, wxT("End Time:"));
    text_ctrl_stayonline_end_time = new wxTextCtrl(notebook_client_pane_stayonline, -1, wxT(""));
    button_stayonline_validate = new wxButton(notebook_client_pane_stayonline, -1, wxT("Validate"));

    set_properties();
    do_layout();
    // end wxGlade
}


void ClientFrame::set_properties()
{
    // begin wxGlade: ClientFrame::set_properties
    SetTitle(wxT("JNetDial Client"));
    // end wxGlade
}


void ClientFrame::do_layout()
{
    // begin wxGlade: ClientFrame::do_layout
    wxBoxSizer* sizer_background = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_stayonline = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_stayonline_timespan = new wxStaticBoxSizer(new wxStaticBox(notebook_client_pane_stayonline, -1, wxT("Time Span")), wxHORIZONTAL);
    wxBoxSizer* sizer_stayonline_end_time = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_stayonline_start_time = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_server = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_connection_control = new wxStaticBoxSizer(new wxStaticBox(notebook_client_pane_server, -1, wxT("Connection Control")), wxHORIZONTAL);
    wxStaticBoxSizer* sizer_connection_status = new wxStaticBoxSizer(new wxStaticBox(notebook_client_pane_server, -1, wxT("Connection Status")), wxHORIZONTAL);
    sizer_connection_status->Add(label_connection_status, 0, wxALL|wxEXPAND, 1);
    sizer_server->Add(sizer_connection_status, 0, wxALL|wxEXPAND, 3);
    sizer_connection_control->Add(button_client_connect, 0, wxALL, 2);
    sizer_connection_control->Add(button_client_disconnect, 0, wxALL, 2);
    sizer_server->Add(sizer_connection_control, 0, wxALIGN_CENTER_HORIZONTAL, 5);
    notebook_client_pane_server->SetAutoLayout(true);
    notebook_client_pane_server->SetSizer(sizer_server);
    sizer_server->Fit(notebook_client_pane_server);
    sizer_server->SetSizeHints(notebook_client_pane_server);
    sizer_stayonline->Add(checkbox_enable_stayonline, 0, wxALL|wxEXPAND, 5);
    sizer_stayonline_start_time->Add(label_stayonline_start_time, 0, 0, 0);
    sizer_stayonline_start_time->Add(text_ctrl_stayonline_start_time, 0, 0, 0);
    sizer_stayonline_timespan->Add(sizer_stayonline_start_time, 1, wxLEFT|wxRIGHT|wxEXPAND, 2);
    sizer_stayonline_end_time->Add(label_stayonline_end_time, 0, 0, 0);
    sizer_stayonline_end_time->Add(text_ctrl_stayonline_end_time, 0, 0, 0);
    sizer_stayonline_timespan->Add(sizer_stayonline_end_time, 1, wxLEFT|wxRIGHT, 2);
    sizer_stayonline->Add(sizer_stayonline_timespan, 0, wxALL|wxEXPAND, 1);
    sizer_stayonline->Add(button_stayonline_validate, 0, wxALL|wxALIGN_RIGHT, 5);
    notebook_client_pane_stayonline->SetAutoLayout(true);
    notebook_client_pane_stayonline->SetSizer(sizer_stayonline);
    sizer_stayonline->Fit(notebook_client_pane_stayonline);
    sizer_stayonline->SetSizeHints(notebook_client_pane_stayonline);
    notebook_client->AddPage(notebook_client_pane_server, wxT("Server"));
    notebook_client->AddPage(notebook_client_pane_stayonline, wxT("StayOnline"));
    sizer_background->Add(new wxNotebookSizer(notebook_client), 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_background);
    sizer_background->Fit(this);
    sizer_background->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}



