// -*- C++ -*- generated by wxGlade 0.2.3 on Sat Oct 04 00:29:25 2003

#include "generated.h"


Avs2OggDialog::Avs2OggDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxTHICK_FRAME)
{
    // begin wxGlade: Avs2OggDialog::Avs2OggDialog
    label_title = new wxStaticText(this, -1, "AVS2Ogg v1.0");
    const wxString list_box_input_files_choices[] = {
        "choice 1"
    };
    list_box_input_files = new wxListBox(this, AVS2Ogg_Input_List, wxDefaultPosition, wxDefaultSize, 1, list_box_input_files_choices, wxLB_SINGLE|wxLB_SORT);
    button_add = new wxButton(this, AVS2Ogg_Add_Button, "Add");
    const wxString radio_box_output_file_type_choices[] = {
        "PCM WAV",
        "Vorbis OGG"
    };
    radio_box_output_file_type = new wxRadioBox(this, -1, "Output Type", wxDefaultPosition, wxDefaultSize, 2, radio_box_output_file_type_choices, 0, wxRA_SPECIFY_ROWS);
    checkbox_normalize = new wxCheckBox(this, -1, "Normalize");
    const wxString combo_box_vorbis_q_choices[] = {
        "0.0",
        "0.1",
        "0.2",
        "0.3",
        "0.4",
        "0.5",
        "0.6",
        "0.7",
        "0.8",
        "0.9",
        "1.0"
    };
    combo_box_vorbis_q = new wxComboBox(this, -1, "", wxDefaultPosition, wxDefaultSize, 11, combo_box_vorbis_q_choices, wxCB_DROPDOWN);
    label_1 = new wxStaticText(this, -1, "Output Filename:");
    text_ctrl_output_filename = new wxTextCtrl(this, -1, "");
    button_start = new wxButton(this, AVS2Ogg_Start_Button, "Start");
    button_close = new wxButton(this, wxID_CANCEL, "Close");

    set_properties();
    do_layout();
    // end wxGlade
}


void Avs2OggDialog::set_properties()
{
    // begin wxGlade: Avs2OggDialog::set_properties
    SetTitle("AVS2Ogg v1.0");
    list_box_input_files->SetSelection(0);
    radio_box_output_file_type->SetSelection(0);
    combo_box_vorbis_q->SetSelection(4);
    // end wxGlade
}


void Avs2OggDialog::do_layout()
{
    // begin wxGlade: Avs2OggDialog::do_layout
    wxBoxSizer* sizer_base = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_buttons = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* sizer_option = new wxStaticBoxSizer(new wxStaticBox(this, -1, "Input File Options"), wxHORIZONTAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_other_options = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_vorbis_quality = new wxStaticBoxSizer(new wxStaticBox(this, -1, "Vorbis Quality"), wxHORIZONTAL);
    wxStaticBoxSizer* sizer_input = new wxStaticBoxSizer(new wxStaticBox(this, -1, "Input AVS Files"), wxHORIZONTAL);
    wxBoxSizer* sizer_input_buttons = new wxBoxSizer(wxVERTICAL);
    sizer_base->Add(label_title, 0, wxTOP|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 3);
    sizer_input->Add(list_box_input_files, 2, wxALL|wxEXPAND, 1);
    sizer_input_buttons->Add(button_add, 0, 0, 0);
    sizer_input->Add(sizer_input_buttons, 0, wxALIGN_BOTTOM, 0);
    sizer_base->Add(sizer_input, 1, wxALL|wxEXPAND, 1);
    sizer_6->Add(radio_box_output_file_type, 0, 0, 0);
    sizer_other_options->Add(checkbox_normalize, 0, wxALL, 3);
    sizer_vorbis_quality->Add(combo_box_vorbis_q, 0, 0, 0);
    sizer_other_options->Add(sizer_vorbis_quality, 0, wxALL, 2);
    sizer_6->Add(sizer_other_options, 0, wxALL, 1);
    sizer_5->Add(sizer_6, 0, wxALL|wxEXPAND, 1);
    sizer_5->Add(label_1, 0, wxLEFT, 1);
    sizer_5->Add(text_ctrl_output_filename, 0, wxEXPAND, 0);
    sizer_option->Add(sizer_5, 1, wxEXPAND, 0);
    sizer_base->Add(sizer_option, 0, wxALL|wxEXPAND, 1);
    sizer_buttons->Add(button_start, 0, wxALL, 2);
    sizer_buttons->Add(button_close, 0, wxALL, 2);
    sizer_base->Add(sizer_buttons, 0, wxALL|wxALIGN_RIGHT, 1);
    SetAutoLayout(true);
    SetSizer(sizer_base);
    sizer_base->Fit(this);
    sizer_base->SetSizeHints(this);
    Layout();
    // end wxGlade
}






