/*
 * VideoSquirrelDatabaseViewer.java
 *
 * Created on June 26, 2003, 12:20 AM
 */

/**
 *
 * @author  Jory
 */

//import VideoSquirrel.*;
import java.lang.*;
import java.io.*;
import java.util.*;
import javax.swing.*;

public class VideoSquirrelDatabaseViewer extends javax.swing.JDialog {  
    protected String databaseFilename;    
    protected VideoSquirrelDatabaseReader videoDatabase;
    protected long recordCount;
    
    /** Creates new form VideoSquirrelDatabaseViewer */
    public VideoSquirrelDatabaseViewer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
              
        jList1Model = new DefaultListModel();        
        jList1 = new JList(jList1Model);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        
        jScrollPane1 = new JScrollPane(jList1);   
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 131));
        jSplitPane1.setLeftComponent(jScrollPane1);
                
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        videoDatabase = new VideoSquirrelDatabaseReader();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jFileChooser1 = new javax.swing.JFileChooser();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1Model = new javax.swing.DefaultListModel();
        jList1 = new javax.swing.JList();
        jList1 = new javax.swing.JList(jList1Model);
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItemExit = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridLayout(1, 1, 5, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Video Squirrel Database Java View");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jSplitPane1.setDividerSize(9);
        jScrollPane1.setNextFocusableComponent(jList1);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 131));
        jList1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1))));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jList1.setMinimumSize(new java.awt.Dimension(50, 50));
        jList1.setPreferredSize(new java.awt.Dimension(100, 2000));
        jList1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jList1ComponentResized(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 67));
        jScrollPane2.setViewportView(jEditorPane1);

        jSplitPane1.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane1);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItemOpen);

        jMenu1.add(jSeparator1);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void jList1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jList1ComponentResized
        // Add your handling code here:
        //jScrollPane1.setViewportView(jList1);
        //jScrollPane1.setBounds(jList1.getBounds());
        //jScrollPane1.setViewportView(jList1);
    }//GEN-LAST:event_jList1ComponentResized

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // Add your handling code here:
        
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // Add your handling code here:

    }//GEN-LAST:event_jList1MouseClicked

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // Add your handling code here:

        jFileChooser1.showOpenDialog(this);
        File selectedFile = jFileChooser1.getSelectedFile();
        this.setTitle("Opening: " + selectedFile.getPath());
        
        videoDatabase = new VideoSquirrelDatabaseReader();
        videoDatabase.LoadDatabase(selectedFile.getPath());
        
        jList1Model.clear();         
        ArrayList uidList = videoDatabase.GetUIDList(); 
        
        //jList1.setMinimumSize(new java.awt.Dimension(1000, (jList1.getFixedCellHeight()+1)*uidList.size()));
        for (int v = 0; v < uidList.size(); v++) {
            Object currentUID = (Object)uidList.get(v);
            jList1Model.addElement(currentUID);
        }
        
        //jList1.setSize(new java.awt.Dimension(1000, (jList1.getFixedCellHeight()+1)*uidList.size()));
        //jScrollPane1.setSize(jList1.getSize());
        
        //jScrollPane1.scrollRectToVisible(jList1.getCellBounds(0, uidList.size()));         
        //jScrollPane1.scrollVertically(jList1, jList1.getCellBounds(0, uidList.size()));         
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // Add your handling code here:        
        try {
            Object objSelectedItem = (Object)jList1.getSelectedValue();            
            jEditorPane1.setContentType("text/html");
            jEditorPane1.setText(videoDatabase.GetByUID(objSelectedItem.hashCode()));
            jEditorPane1.setCaretPosition(0);
            //int lastLinePos = jTextArea1.getLineEndOffset(jTextArea1.getLineCount()-1);
            //jTextArea1.replaceRange(selectedItem.GetFormattedString(), 0, lastLinePos);        
        } catch (Exception prob){
            //Error
            prob.printStackTrace();
        }        
    }//GEN-LAST:event_jList1ValueChanged
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new VideoSquirrelDatabaseViewer(new javax.swing.JFrame(), true).show();
    }
    
    private javax.swing.DefaultListModel jList1Model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    
}
